# Generated by Django 5.2.4 on 2026-02-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=64)),
                ('license_key', models.CharField(max_length=64, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('generated_by', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='generated', max_length=32)),
                ('source', models.CharField(default='license_manager_web', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
