# Generated by Django 5.2.4 on 2026-02-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlicense',
            name='valid_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
