# Generated by Django 5.2.4 on 2026-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_generatedlicense_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_uri', models.TextField(blank=True)),
                ('mongo_db', models.CharField(blank=True, max_length=128)),
                ('mongo_collection', models.CharField(blank=True, max_length=128)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License Runtime Config',
                'verbose_name_plural': 'License Runtime Config',
            },
        ),
    ]
